# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareGoPayCheckout = channel.unary_unary(
                '/payment.PaymentService/PrepareGoPayCheckout',
                request_serializer=payment__pb2.PrepareGoPayCheckoutRequest.SerializeToString,
                response_deserializer=payment__pb2.PrepareGoPayResponse.FromString,
                _registered_method=True)
        self.RefreshPrepareGoPayCheckout = channel.unary_unary(
                '/payment.PaymentService/RefreshPrepareGoPayCheckout',
                request_serializer=payment__pb2.RefreshPrepareGoPayCheckoutRequest.SerializeToString,
                response_deserializer=payment__pb2.PrepareGoPayResponse.FromString,
                _registered_method=True)
        self.PrepareGoPayLink = channel.unary_unary(
                '/payment.PaymentService/PrepareGoPayLink',
                request_serializer=payment__pb2.PrepareGoPayLinkRequest.SerializeToString,
                response_deserializer=payment__pb2.PrepareGoPayResponse.FromString,
                _registered_method=True)
        self.PrepareGoPay = channel.unary_unary(
                '/payment.PaymentService/PrepareGoPay',
                request_serializer=payment__pb2.PrepareGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.PrepareGoPayResponse.FromString,
                _registered_method=True)
        self.StartPreparedGoPay = channel.unary_unary(
                '/payment.PaymentService/StartPreparedGoPay',
                request_serializer=payment__pb2.StartPreparedGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.StartGoPayResponse.FromString,
                _registered_method=True)
        self.StartGoPay = channel.unary_unary(
                '/payment.PaymentService/StartGoPay',
                request_serializer=payment__pb2.StartGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.StartGoPayResponse.FromString,
                _registered_method=True)
        self.CreateCheckoutLink = channel.unary_unary(
                '/payment.PaymentService/CreateCheckoutLink',
                request_serializer=payment__pb2.CreateCheckoutLinkRequest.SerializeToString,
                response_deserializer=payment__pb2.CreateCheckoutLinkResponse.FromString,
                _registered_method=True)
        self.ProbePlusTrial = channel.unary_unary(
                '/payment.PaymentService/ProbePlusTrial',
                request_serializer=payment__pb2.ProbePlusTrialPaymentRequest.SerializeToString,
                response_deserializer=payment__pb2.ProbePlusTrialPaymentResponse.FromString,
                _registered_method=True)
        self.ProbeTier = channel.unary_unary(
                '/payment.PaymentService/ProbeTier',
                request_serializer=payment__pb2.ProbeTierPaymentRequest.SerializeToString,
                response_deserializer=payment__pb2.ProbeTierPaymentResponse.FromString,
                _registered_method=True)
        self.CompleteGoPay = channel.unary_unary(
                '/payment.PaymentService/CompleteGoPay',
                request_serializer=payment__pb2.CompleteGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.GoPayResponse.FromString,
                _registered_method=True)
        self.ResendGoPayOTP = channel.unary_unary(
                '/payment.PaymentService/ResendGoPayOTP',
                request_serializer=payment__pb2.ResendGoPayOTPRequest.SerializeToString,
                response_deserializer=payment__pb2.ResendGoPayOTPResponse.FromString,
                _registered_method=True)
        self.ConfirmGoPayPayment = channel.unary_unary(
                '/payment.PaymentService/ConfirmGoPayPayment',
                request_serializer=payment__pb2.ConfirmGoPayPaymentRequest.SerializeToString,
                response_deserializer=payment__pb2.GoPayResponse.FromString,
                _registered_method=True)
        self.CancelGoPay = channel.unary_unary(
                '/payment.PaymentService/CancelGoPay',
                request_serializer=payment__pb2.CancelGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.CancelGoPayResponse.FromString,
                _registered_method=True)
        self.UnlinkGoPay = channel.unary_unary(
                '/payment.PaymentService/UnlinkGoPay',
                request_serializer=payment__pb2.UnlinkGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.UnlinkGoPayResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrepareGoPayCheckout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshPrepareGoPayCheckout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareGoPayLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPreparedGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckoutLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProbePlusTrial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProbeTier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResendGoPayOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmGoPayPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareGoPayCheckout': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareGoPayCheckout,
                    request_deserializer=payment__pb2.PrepareGoPayCheckoutRequest.FromString,
                    response_serializer=payment__pb2.PrepareGoPayResponse.SerializeToString,
            ),
            'RefreshPrepareGoPayCheckout': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshPrepareGoPayCheckout,
                    request_deserializer=payment__pb2.RefreshPrepareGoPayCheckoutRequest.FromString,
                    response_serializer=payment__pb2.PrepareGoPayResponse.SerializeToString,
            ),
            'PrepareGoPayLink': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareGoPayLink,
                    request_deserializer=payment__pb2.PrepareGoPayLinkRequest.FromString,
                    response_serializer=payment__pb2.PrepareGoPayResponse.SerializeToString,
            ),
            'PrepareGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareGoPay,
                    request_deserializer=payment__pb2.PrepareGoPayRequest.FromString,
                    response_serializer=payment__pb2.PrepareGoPayResponse.SerializeToString,
            ),
            'StartPreparedGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPreparedGoPay,
                    request_deserializer=payment__pb2.StartPreparedGoPayRequest.FromString,
                    response_serializer=payment__pb2.StartGoPayResponse.SerializeToString,
            ),
            'StartGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGoPay,
                    request_deserializer=payment__pb2.StartGoPayRequest.FromString,
                    response_serializer=payment__pb2.StartGoPayResponse.SerializeToString,
            ),
            'CreateCheckoutLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckoutLink,
                    request_deserializer=payment__pb2.CreateCheckoutLinkRequest.FromString,
                    response_serializer=payment__pb2.CreateCheckoutLinkResponse.SerializeToString,
            ),
            'ProbePlusTrial': grpc.unary_unary_rpc_method_handler(
                    servicer.ProbePlusTrial,
                    request_deserializer=payment__pb2.ProbePlusTrialPaymentRequest.FromString,
                    response_serializer=payment__pb2.ProbePlusTrialPaymentResponse.SerializeToString,
            ),
            'ProbeTier': grpc.unary_unary_rpc_method_handler(
                    servicer.ProbeTier,
                    request_deserializer=payment__pb2.ProbeTierPaymentRequest.FromString,
                    response_serializer=payment__pb2.ProbeTierPaymentResponse.SerializeToString,
            ),
            'CompleteGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteGoPay,
                    request_deserializer=payment__pb2.CompleteGoPayRequest.FromString,
                    response_serializer=payment__pb2.GoPayResponse.SerializeToString,
            ),
            'ResendGoPayOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.ResendGoPayOTP,
                    request_deserializer=payment__pb2.ResendGoPayOTPRequest.FromString,
                    response_serializer=payment__pb2.ResendGoPayOTPResponse.SerializeToString,
            ),
            'ConfirmGoPayPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmGoPayPayment,
                    request_deserializer=payment__pb2.ConfirmGoPayPaymentRequest.FromString,
                    response_serializer=payment__pb2.GoPayResponse.SerializeToString,
            ),
            'CancelGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGoPay,
                    request_deserializer=payment__pb2.CancelGoPayRequest.FromString,
                    response_serializer=payment__pb2.CancelGoPayResponse.SerializeToString,
            ),
            'UnlinkGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkGoPay,
                    request_deserializer=payment__pb2.UnlinkGoPayRequest.FromString,
                    response_serializer=payment__pb2.UnlinkGoPayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareGoPayCheckout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/PrepareGoPayCheckout',
            payment__pb2.PrepareGoPayCheckoutRequest.SerializeToString,
            payment__pb2.PrepareGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshPrepareGoPayCheckout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/RefreshPrepareGoPayCheckout',
            payment__pb2.RefreshPrepareGoPayCheckoutRequest.SerializeToString,
            payment__pb2.PrepareGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareGoPayLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/PrepareGoPayLink',
            payment__pb2.PrepareGoPayLinkRequest.SerializeToString,
            payment__pb2.PrepareGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/PrepareGoPay',
            payment__pb2.PrepareGoPayRequest.SerializeToString,
            payment__pb2.PrepareGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPreparedGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/StartPreparedGoPay',
            payment__pb2.StartPreparedGoPayRequest.SerializeToString,
            payment__pb2.StartGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/StartGoPay',
            payment__pb2.StartGoPayRequest.SerializeToString,
            payment__pb2.StartGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCheckoutLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CreateCheckoutLink',
            payment__pb2.CreateCheckoutLinkRequest.SerializeToString,
            payment__pb2.CreateCheckoutLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProbePlusTrial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ProbePlusTrial',
            payment__pb2.ProbePlusTrialPaymentRequest.SerializeToString,
            payment__pb2.ProbePlusTrialPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProbeTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ProbeTier',
            payment__pb2.ProbeTierPaymentRequest.SerializeToString,
            payment__pb2.ProbeTierPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CompleteGoPay',
            payment__pb2.CompleteGoPayRequest.SerializeToString,
            payment__pb2.GoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResendGoPayOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ResendGoPayOTP',
            payment__pb2.ResendGoPayOTPRequest.SerializeToString,
            payment__pb2.ResendGoPayOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmGoPayPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ConfirmGoPayPayment',
            payment__pb2.ConfirmGoPayPaymentRequest.SerializeToString,
            payment__pb2.GoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CancelGoPay',
            payment__pb2.CancelGoPayRequest.SerializeToString,
            payment__pb2.CancelGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/UnlinkGoPay',
            payment__pb2.UnlinkGoPayRequest.SerializeToString,
            payment__pb2.UnlinkGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
